python ./run_ner.py \
--data_dir ../data \
--model_name_or_path {model} \
--labels ../data/labels.txt \
--output_dir ./output \
--max_seq_length 128 \
--num_train_epochs 30 \
--per_device_train_batch_size 32 \
--seed 1 \
--logging_strategy "epoch" \
--logging_steps 1 \
--load_best_model_at_end True \
--save_total_limit 2 \
--crf True \
--save_strategy "no" \
--do_predict true \
--overwrite_output_dir